version: '3.8'
services:
  app:
    build:
      context: .
      args:
        API_KEY: ${API_KEY}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TMDB_KEY=${API_KEY}
